// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: my.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WebServer.Protos
{

    /// <summary>Holder for reflection information generated from my.proto</summary>
    public static partial class MyReflection
    {

        #region Descriptor
        /// <summary>File descriptor for my.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static MyReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "CghteS5wcm90byKJAQoNQ2hhcmFjdGVyRGF0YRINCgVsZXZlbBgBIAEoBRIL",
                  "CgNleHAYAiABKAUSEgoKcGxheWVyTmFtZRgDIAEoCRIMCgRnb2xkGAQgASgF",
                  "EicKDndlYXBvblNhdmVEYXRhGAUgASgLMg8uV2VhcG9uU2F2ZURhdGESEQoJ",
                  "cmlmbGVBbW1vGAYgASgFIrMBCg5XZWFwb25TYXZlRGF0YRITCgt3ZWFwb25M",
                  "ZXZlbBgBIAEoBRIeChZ3ZWFwb25FbmhhbmNlbWVudExldmVsGAIgASgFEi4K",
                  "CndlYXBvblR5cGUYAyABKA4yGi5XZWFwb25TYXZlRGF0YS5XZWFwb25UeXBl",
                  "IjwKCldlYXBvblR5cGUSDQoJRVdUX1JJRkxFEAASDgoKRVdUX1BJU1RPTBAB",
                  "Eg8KC0VXVF9TSE9UR1VOEAJCE6oCEFdlYlNlcnZlci5Qcm90b3NiBnByb3Rv",
                  "Mw=="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WebServer.Protos.CharacterData), global::WebServer.Protos.CharacterData.Parser, new[]{ "Level", "Exp", "PlayerName", "Gold", "WeaponSaveData", "RifleAmmo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WebServer.Protos.WeaponSaveData), global::WebServer.Protos.WeaponSaveData.Parser, new[]{ "WeaponLevel", "WeaponEnhancementLevel", "WeaponType" }, null, new[]{ typeof(global::WebServer.Protos.WeaponSaveData.Types.WeaponType) }, null, null)
                }));
        }
        #endregion

    }
    #region Messages
    public sealed partial class CharacterData : pb::IMessage<CharacterData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<CharacterData> _parser = new pb::MessageParser<CharacterData>(() => new CharacterData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<CharacterData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::WebServer.Protos.MyReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CharacterData()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CharacterData(CharacterData other) : this()
        {
            level_ = other.level_;
            exp_ = other.exp_;
            playerName_ = other.playerName_;
            gold_ = other.gold_;
            weaponSaveData_ = other.weaponSaveData_ != null ? other.weaponSaveData_.Clone() : null;
            rifleAmmo_ = other.rifleAmmo_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CharacterData Clone()
        {
            return new CharacterData(this);
        }

        /// <summary>Field number for the "level" field.</summary>
        public const int LevelFieldNumber = 1;
        private int level_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Level
        {
            get { return level_; }
            set
            {
                level_ = value;
            }
        }

        /// <summary>Field number for the "exp" field.</summary>
        public const int ExpFieldNumber = 2;
        private int exp_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Exp
        {
            get { return exp_; }
            set
            {
                exp_ = value;
            }
        }

        /// <summary>Field number for the "playerName" field.</summary>
        public const int PlayerNameFieldNumber = 3;
        private string playerName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string PlayerName
        {
            get { return playerName_; }
            set
            {
                playerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "gold" field.</summary>
        public const int GoldFieldNumber = 4;
        private int gold_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Gold
        {
            get { return gold_; }
            set
            {
                gold_ = value;
            }
        }

        /// <summary>Field number for the "weaponSaveData" field.</summary>
        public const int WeaponSaveDataFieldNumber = 5;
        private global::WebServer.Protos.WeaponSaveData weaponSaveData_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::WebServer.Protos.WeaponSaveData WeaponSaveData
        {
            get { return weaponSaveData_; }
            set
            {
                weaponSaveData_ = value;
            }
        }

        /// <summary>Field number for the "rifleAmmo" field.</summary>
        public const int RifleAmmoFieldNumber = 6;
        private int rifleAmmo_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int RifleAmmo
        {
            get { return rifleAmmo_; }
            set
            {
                rifleAmmo_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as CharacterData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(CharacterData other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Level != other.Level) return false;
            if (Exp != other.Exp) return false;
            if (PlayerName != other.PlayerName) return false;
            if (Gold != other.Gold) return false;
            if (!object.Equals(WeaponSaveData, other.WeaponSaveData)) return false;
            if (RifleAmmo != other.RifleAmmo) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Level != 0) hash ^= Level.GetHashCode();
            if (Exp != 0) hash ^= Exp.GetHashCode();
            if (PlayerName.Length != 0) hash ^= PlayerName.GetHashCode();
            if (Gold != 0) hash ^= Gold.GetHashCode();
            if (weaponSaveData_ != null) hash ^= WeaponSaveData.GetHashCode();
            if (RifleAmmo != 0) hash ^= RifleAmmo.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Level != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Level);
      }
      if (Exp != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Exp);
      }
      if (PlayerName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PlayerName);
      }
      if (Gold != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Gold);
      }
      if (weaponSaveData_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(WeaponSaveData);
      }
      if (RifleAmmo != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(RifleAmmo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Level != 0)
            {
                output.WriteRawTag(8);
                output.WriteInt32(Level);
            }
            if (Exp != 0)
            {
                output.WriteRawTag(16);
                output.WriteInt32(Exp);
            }
            if (PlayerName.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteString(PlayerName);
            }
            if (Gold != 0)
            {
                output.WriteRawTag(32);
                output.WriteInt32(Gold);
            }
            if (weaponSaveData_ != null)
            {
                output.WriteRawTag(42);
                output.WriteMessage(WeaponSaveData);
            }
            if (RifleAmmo != 0)
            {
                output.WriteRawTag(48);
                output.WriteInt32(RifleAmmo);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Level != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
            }
            if (Exp != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(Exp);
            }
            if (PlayerName.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerName);
            }
            if (Gold != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gold);
            }
            if (weaponSaveData_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(WeaponSaveData);
            }
            if (RifleAmmo != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(RifleAmmo);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(CharacterData other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Level != 0)
            {
                Level = other.Level;
            }
            if (other.Exp != 0)
            {
                Exp = other.Exp;
            }
            if (other.PlayerName.Length != 0)
            {
                PlayerName = other.PlayerName;
            }
            if (other.Gold != 0)
            {
                Gold = other.Gold;
            }
            if (other.weaponSaveData_ != null)
            {
                if (weaponSaveData_ == null)
                {
                    WeaponSaveData = new global::WebServer.Protos.WeaponSaveData();
                }
                WeaponSaveData.MergeFrom(other.WeaponSaveData);
            }
            if (other.RifleAmmo != 0)
            {
                RifleAmmo = other.RifleAmmo;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Level = input.ReadInt32();
            break;
          }
          case 16: {
            Exp = input.ReadInt32();
            break;
          }
          case 26: {
            PlayerName = input.ReadString();
            break;
          }
          case 32: {
            Gold = input.ReadInt32();
            break;
          }
          case 42: {
            if (weaponSaveData_ == null) {
              WeaponSaveData = new global::WebServer.Protos.WeaponSaveData();
            }
            input.ReadMessage(WeaponSaveData);
            break;
          }
          case 48: {
            RifleAmmo = input.ReadInt32();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Level = input.ReadInt32();
                            break;
                        }
                    case 16:
                        {
                            Exp = input.ReadInt32();
                            break;
                        }
                    case 26:
                        {
                            PlayerName = input.ReadString();
                            break;
                        }
                    case 32:
                        {
                            Gold = input.ReadInt32();
                            break;
                        }
                    case 42:
                        {
                            if (weaponSaveData_ == null)
                            {
                                WeaponSaveData = new global::WebServer.Protos.WeaponSaveData();
                            }
                            input.ReadMessage(WeaponSaveData);
                            break;
                        }
                    case 48:
                        {
                            RifleAmmo = input.ReadInt32();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class WeaponSaveData : pb::IMessage<WeaponSaveData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<WeaponSaveData> _parser = new pb::MessageParser<WeaponSaveData>(() => new WeaponSaveData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<WeaponSaveData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::WebServer.Protos.MyReflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public WeaponSaveData()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public WeaponSaveData(WeaponSaveData other) : this()
        {
            weaponLevel_ = other.weaponLevel_;
            weaponEnhancementLevel_ = other.weaponEnhancementLevel_;
            weaponType_ = other.weaponType_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public WeaponSaveData Clone()
        {
            return new WeaponSaveData(this);
        }

        /// <summary>Field number for the "weaponLevel" field.</summary>
        public const int WeaponLevelFieldNumber = 1;
        private int weaponLevel_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int WeaponLevel
        {
            get { return weaponLevel_; }
            set
            {
                weaponLevel_ = value;
            }
        }

        /// <summary>Field number for the "weaponEnhancementLevel" field.</summary>
        public const int WeaponEnhancementLevelFieldNumber = 2;
        private int weaponEnhancementLevel_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int WeaponEnhancementLevel
        {
            get { return weaponEnhancementLevel_; }
            set
            {
                weaponEnhancementLevel_ = value;
            }
        }

        /// <summary>Field number for the "weaponType" field.</summary>
        public const int WeaponTypeFieldNumber = 3;
        private global::WebServer.Protos.WeaponSaveData.Types.WeaponType weaponType_ = global::WebServer.Protos.WeaponSaveData.Types.WeaponType.EwtRifle;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::WebServer.Protos.WeaponSaveData.Types.WeaponType WeaponType
        {
            get { return weaponType_; }
            set
            {
                weaponType_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as WeaponSaveData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(WeaponSaveData other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (WeaponLevel != other.WeaponLevel) return false;
            if (WeaponEnhancementLevel != other.WeaponEnhancementLevel) return false;
            if (WeaponType != other.WeaponType) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (WeaponLevel != 0) hash ^= WeaponLevel.GetHashCode();
            if (WeaponEnhancementLevel != 0) hash ^= WeaponEnhancementLevel.GetHashCode();
            if (WeaponType != global::WebServer.Protos.WeaponSaveData.Types.WeaponType.EwtRifle) hash ^= WeaponType.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (WeaponLevel != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(WeaponLevel);
      }
      if (WeaponEnhancementLevel != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(WeaponEnhancementLevel);
      }
      if (WeaponType != global::WebServer.Protos.WeaponSaveData.Types.WeaponType.EwtRifle) {
        output.WriteRawTag(24);
        output.WriteEnum((int) WeaponType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (WeaponLevel != 0)
            {
                output.WriteRawTag(8);
                output.WriteInt32(WeaponLevel);
            }
            if (WeaponEnhancementLevel != 0)
            {
                output.WriteRawTag(16);
                output.WriteInt32(WeaponEnhancementLevel);
            }
            if (WeaponType != global::WebServer.Protos.WeaponSaveData.Types.WeaponType.EwtRifle)
            {
                output.WriteRawTag(24);
                output.WriteEnum((int)WeaponType);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (WeaponLevel != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(WeaponLevel);
            }
            if (WeaponEnhancementLevel != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(WeaponEnhancementLevel);
            }
            if (WeaponType != global::WebServer.Protos.WeaponSaveData.Types.WeaponType.EwtRifle)
            {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)WeaponType);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(WeaponSaveData other)
        {
            if (other == null)
            {
                return;
            }
            if (other.WeaponLevel != 0)
            {
                WeaponLevel = other.WeaponLevel;
            }
            if (other.WeaponEnhancementLevel != 0)
            {
                WeaponEnhancementLevel = other.WeaponEnhancementLevel;
            }
            if (other.WeaponType != global::WebServer.Protos.WeaponSaveData.Types.WeaponType.EwtRifle)
            {
                WeaponType = other.WeaponType;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            WeaponLevel = input.ReadInt32();
            break;
          }
          case 16: {
            WeaponEnhancementLevel = input.ReadInt32();
            break;
          }
          case 24: {
            WeaponType = (global::WebServer.Protos.WeaponSaveData.Types.WeaponType) input.ReadEnum();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            WeaponLevel = input.ReadInt32();
                            break;
                        }
                    case 16:
                        {
                            WeaponEnhancementLevel = input.ReadInt32();
                            break;
                        }
                    case 24:
                        {
                            WeaponType = (global::WebServer.Protos.WeaponSaveData.Types.WeaponType)input.ReadEnum();
                            break;
                        }
                }
            }
        }
#endif

        #region Nested types
        /// <summary>Container for nested types declared in the WeaponSaveData message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types
        {
            public enum WeaponType
            {
                [pbr::OriginalName("EWT_RIFLE")] EwtRifle = 0,
                [pbr::OriginalName("EWT_PISTOL")] EwtPistol = 1,
                [pbr::OriginalName("EWT_SHOTGUN")] EwtShotgun = 2,
            }

        }
        #endregion

    }

    #endregion

}

#endregion Designer generated code
